[build]
  command = "npm run build"
  publish = "dist/website"
  environment = { NODE_VERSION = "16" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing.html]
  pretty_urls = false